### ISSUE TITLE
Support for user-defined prompt and pass through (two-factor auth)

### ISSUE THREAD

**Issue by chitoku-k** [xxh/xxh#92] opened 2020-06-21 06:37 UTC
**Is your feature request related to a problem? Please describe.**
Some of my servers enable two-step verification when connecting to SSH. That generally works out of the box if a client simply prints what server sends and a client directly sends what a user types. However xxh firstly uses pexpect to collect host information and it stucks when a connection unexpectedly blocks with something like these:
```
Verification code:
```
```
We've sent a notification to your mobile device. Please respond to continue.
```

**Describe the solution you'd like**
Let xxh accept user-defined patterns to either prompt or pass through server output. Configuration could look like:
```yml
hosts:
  .*:
    ++prompt-input: Verification code:
    ++prompt-pass-through: Please respond to continue.
```

**Describe alternatives you've considered**
No idea.

**Additional context**
Some code could be inserted here:
https://github.com/xxh/xxh/blob/04019d1/xxh_xxh/xxh.py#L105-L190
```python
if i == 7:
    # Input
    print((sess.before + sess.after).decode("utf-8"), end='')
    sess.sendline(input())

if i == 8:
    # Pass through
    print((sess.before + sess.after).decode("utf-8"), end='')
```

**For community:**
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment] 2020-06-22 16:37
I can confirm this. There is no good support for 2FA scenario in xxh. The workaround is to `ssh myhost` before `xxh myhost` to cache the connection auth.

We use pexpect to catch password to avoid typing the password every ssh command we send to the server. Probably the common solution for case 2FA+key is to have the option to disable pexpect. 

@chitoku-k could you please do `ssh yourhost` and put here the log to understand your case step by step.

**Comment by chitoku-k** [comment] 2020-06-22 16:54
Yes, I now preauth the server by `ControlMaster` to keep my connection alive even I shortly disconnected from a remote server. And the output is like this:
```
[home  ~  $] ssh host
Verification code: 000000
Last login: Mon Jun 22 22:18:28 2020

[host  ~  $ ] echo Now I am on the remote
```
When I connect to host it authenticates me by the public key and then it prompts me to type in a two-factor authentication code so I can log in to it.

**Comment by anki-code** [comment] 2020-06-22 18:54
Am I understand right that "Verification code:" prompt appears after authorization by key?

**Comment by chitoku-k** [comment] 2020-06-23 01:45
@anki-code You are right.

**Comment by anki-code** [comment] 2020-06-25 08:46
@chitoku-k I can't repeat your case because I haven't this kind of 2FA. But I've added `++pexpect-disable` option to the master. Please try to update and run:
```
pip install -U git+https://github.com/xxh/xxh
xxh host_with_2fa ++pexpect-disable
```
If you use key without password I expect that ssh will ask you about 2FA code once and then use the cached connection.

**Comment by chitoku-k** [comment] 2020-06-25 10:23
@anki-code Great! It works like a charm for me as you've described.

**Comment by anki-code** [comment] 2020-06-27 07:17
Great! Close this until new case with 2FA.

**Closed by anki-code** 2020-06-27 07:17 UTC
Labels: new feature

**Comment by omar-binary** [comment] 2021-02-19 04:41
Hey, I'm getting an issue with 2FA it's going in an endless loop with 
`Authenticated with partial success`

<img width="608" alt="Screenshot 2021-02-19 at 12 39 08 PM" src="https://user-images.githubusercontent.com/48001122/108458345-77390180-72af-11eb-8d71-9d0598eee4b8.png">

this is my command:

```bash
xxh ++pexpect-disable +vv -i ~/.ssh/some_key any_host_with_2fa
```

**Comment by anki-code** [comment] 2021-02-21 06:55
Hi @omar-binary! 
1. What is your source host's OS  and what is your target host's OS?

2. I don't like the line: 
```
bash: /SOME_PATH/.xxh/.xxh/shells/xxh-shell-zsh/build/entrypoint.sh: No such file or directory
```
What if you add `+if` to force reinstall or `+iff` to force full reinstall (target `~/.xxh` directory will be completely erased)?

3. Finally is there a way to repeat your case using docker (i.e. [xxh-dev](https://github.com/xxh/xxh-dev) environment)?
